baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Now Playing"
author = "Glitch.Family"
mainSections = ["a"]
paginate = 16
disableKinds = ["taxonomy", "taxonomyTerm"]

[imaging]
quality = 95
[security]
    [security.funcs]
    getenv = [ "^HUGO_", "CONTEXT", "URL" ]
