baseURL = "http://127.0.0.1:8080/"
languageCode = "en-us"
title = "Now Playing"
author = "the Glitch Family"
mainSections = ["musics"]
paginate = 16
disableKinds = ["taxonomy", "taxonomyTerm"]

[imaging]
quality = 95
[security]
    [security.funcs]
    getenv = [ "^HUGO_", "CONTEXT" ]
