baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Now Playing"
mainSections = ["a"]
paginate = 16
disableKinds = ["taxonomy"]
[params]
  description = "Collection of Handpicked Albums by Guérilla.Studio"
  [params.author]
    name = "Guérilla.Studio"
    url = "https://guerilla.studio"
  [params.creator]
    name = "Guérilla.Studio"
    url = "https://guerilla.studio"

[imaging]
quality = 95
[security]
  [security.funcs]
  getenv = [ "^HUGO_", "CONTEXT", "URL" ]
