[build]
  publish = "public"
  command = "hugo -b $URL"
[build.environment]
  HUGO_VERSION = "0.95.0"


[context.production.environment]
  HUGO_ENV = "production"
  command = "hugo -b $URL"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  force = true
  from = "/a"
  to = "/"

# Old urls

[[redirects]]
  force = true
  from = "/musics"
  to = "/"

[[redirects]]
  force = true
  from = "/musics/*"
  to = "/a/:splat"

[[redirects]]
  force = true
  from = "/page:*"
  to = "/page/:splat"
